
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Ingresar extends javax.swing.JFrame {
    private Multa multaExistente;  // null si creamos nueva multa
    private Multas parentFrame;
    private boolean modoEdicion;
 public JTextArea TextM;

public Ingresar(Multas parent, Multa multa) {
    this.parentFrame = parent;
    this.multaExistente = multa;
    this.modoEdicion = true;
    initComponents();
    cargarDatosMulta(multa);
}
       // Constructor para nuevo ingreso
       public Ingresar(Multas parentFrame) {
           this.parentFrame = parentFrame;
           this.multaExistente = null; // No hay multa existente
           initComponents();
       }

    private void cargarDatosMulta(Multa multa) {
        Placa.setText(multa.getPlaca());
        Fecha.setText(multa.getFecha());
        Descripcion.setText(multa.getDescripcion());
        Monto.setText(String.valueOf(multa.getMonto()));
        Depto.setText(multa.getDepartamento());
    }
private void crearOModificarMulta() {
    String placa = Placa.getText().trim();
    String fecha = Fecha.getText().trim();
    String descripcion = Descripcion.getText().trim();
    String montoText = Monto.getText().trim();
    String departamento = Depto.getText().trim();

    if (placa.isEmpty() || fecha.isEmpty() || descripcion.isEmpty() || montoText.isEmpty() || departamento.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    long startTime = System.currentTimeMillis(); // Tiempo de inicio en milisegundos

    try {
        double monto = Double.parseDouble(montoText);
        if (modoEdicion && multaExistente != null) {
            // Modificar la multa existente
            multaExistente.setPlaca(placa);
            multaExistente.setFecha(fecha);
            multaExistente.setDescripcion(descripcion);
            multaExistente.setMonto(monto);
            multaExistente.setDepartamento(departamento);
            JOptionPane.showMessageDialog(this, "Multa modificada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Crear nueva multa
            Multa nuevaMulta = new Multa(placa, fecha, descripcion, monto, departamento);
            // Asegúrate de pasar el JTextArea al método agregarMulta
            parentFrame.listaMultas.agregarMulta(nuevaMulta, parentFrame.getTextM());
            JOptionPane.showMessageDialog(this, "Multa creada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }

        long endTime = System.currentTimeMillis(); // Tiempo de fin en milisegundos
        double durationInSeconds = (endTime - startTime) / 1000.0; // Calcular la duración en segundos

        // Mostrar el tiempo en el JTextArea
        parentFrame.getTextM().setText("Tiempo de operación: " + durationInSeconds + " segundos");

        parentFrame.actualizarTabla();
        dispose();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Monto inválido. Por favor, ingrese un número.", "Error de Monto", JOptionPane.ERROR_MESSAGE);
    }
}







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelito = new javax.swing.JPanel();
        P = new javax.swing.JLabel();
        N = new javax.swing.JLabel();
        MO = new javax.swing.JLabel();
        M = new javax.swing.JLabel();
        TRA = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        Placa = new javax.swing.JTextField();
        Fecha = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        Monto = new javax.swing.JTextField();
        Depto = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panelito.setBackground(new java.awt.Color(0, 51, 204));

        P.setText("Placa");

        N.setText("Fecha");

        MO.setText("Descripcion");

        M.setText("Monto");

        TRA.setText("Depto");

        OK.setText("Agregar");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaActionPerformed(evt);
            }
        });

        Fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaActionPerformed(evt);
            }
        });

        Depto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptoActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelitoLayout = new javax.swing.GroupLayout(Panelito);
        Panelito.setLayout(PanelitoLayout);
        PanelitoLayout.setHorizontalGroup(
            PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelitoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(N)
                    .addComponent(P)
                    .addGroup(PanelitoLayout.createSequentialGroup()
                        .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(M)
                            .addComponent(MO)
                            .addComponent(TRA))
                        .addGap(24, 24, 24)
                        .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Depto)
                            .addComponent(Descripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(Fecha)
                            .addComponent(Placa)
                            .addComponent(Monto))))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelitoLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelitoLayout.createSequentialGroup()
                        .addComponent(Salir)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelitoLayout.createSequentialGroup()
                        .addComponent(OK)
                        .addGap(167, 167, 167))))
        );
        PanelitoLayout.setVerticalGroup(
            PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelitoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Salir)
                .addGap(24, 24, 24)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P)
                    .addComponent(Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MO))
                .addGap(58, 58, 58)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M)
                    .addComponent(Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TRA)
                    .addComponent(Depto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(OK)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
       crearOModificarMulta();
    }//GEN-LAST:event_OKActionPerformed

    private void PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaActionPerformed

    }//GEN-LAST:event_PlacaActionPerformed

    private void FechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaActionPerformed

    private void DeptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_SalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Depto;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JTextField Fecha;
    private javax.swing.JLabel M;
    private javax.swing.JLabel MO;
    private javax.swing.JTextField Monto;
    private javax.swing.JLabel N;
    private javax.swing.JButton OK;
    private javax.swing.JLabel P;
    private javax.swing.JPanel Panelito;
    private javax.swing.JTextField Placa;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel TRA;
    // End of variables declaration//GEN-END:variables
}