
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class IngresoT extends javax.swing.JFrame {


private JTextArea TextM;
private boolean modoEdicion = false; // false: crear, true: modificar
private Traspaso traspasoExistente = null;
private Traspasos traspasosFrame;

    public IngresoT(Traspasos parentFrame) {
        this.traspasosFrame = parentFrame;
        this.modoEdicion = false;
        initComponents();
    }
        // Constructor para modificar traspaso existente
    public IngresoT(Traspasos parentFrame, Traspaso traspasoExistente) {
        this.traspasosFrame = parentFrame;
        this.traspasoExistente = traspasoExistente;
        this.modoEdicion = true;
        initComponents();
        cargarDatosTraspaso();
    }
    
        private void cargarDatosTraspaso() {
        if (traspasoExistente != null) {
            Placa.setText(traspasoExistente.getPlaca());
            DpiAnterior.setText(traspasoExistente.getDpiAnterior());
            NombreAnterior.setText(traspasoExistente.getNombreAnterior());
            Fecha.setText(traspasoExistente.getFecha());
            DpiNuevo.setText(traspasoExistente.getDpiNuevo());
            NombreNuevo.setText(traspasoExistente.getNombreNuevo());
            Departamento.setText(traspasoExistente.getDepartamento());
        }
    }
private void crearOModificarTraspaso() {
    String placa = Placa.getText().trim();
    String dpiAnt = DpiAnterior.getText().trim();
    String nombreAnt = NombreAnterior.getText().trim();
    String fecha = Fecha.getText().trim();
    String dpiNuevo = DpiNuevo.getText().trim();
    String nombreNuevo = NombreNuevo.getText().trim();
    String departamento = Departamento.getText().trim();

    // Verificar que todos los campos estén completos
    if (placa.isEmpty() || dpiAnt.isEmpty() || nombreAnt.isEmpty() || fecha.isEmpty() || dpiNuevo.isEmpty() || nombreNuevo.isEmpty() || departamento.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    long startTime = System.currentTimeMillis(); // Tiempo de inicio en milisegundos

    try {
        if (modoEdicion && traspasoExistente != null) {
            // Modificar el traspaso existente
            traspasoExistente.setPlaca(placa);
            traspasoExistente.setDpiAnterior(dpiAnt);
            traspasoExistente.setNombreAnterior(nombreAnt);
            traspasoExistente.setFecha(fecha);
            traspasoExistente.setDpiNuevo(dpiNuevo);
            traspasoExistente.setNombreNuevo(nombreNuevo);
            traspasoExistente.setDepartamento(departamento);
            JOptionPane.showMessageDialog(this, "Traspaso modificado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Crear nuevo traspaso
            Traspaso nuevoTraspaso = new Traspaso(placa, dpiAnt, nombreAnt, fecha, dpiNuevo, nombreNuevo, departamento);
            // Asegúrate de pasar el JTextArea al método agregarNuevoTraspaso
            traspasosFrame.agregarNuevoTraspaso(nuevoTraspaso);
            JOptionPane.showMessageDialog(this, "Traspaso creado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        }

        long endTime = System.currentTimeMillis(); // Tiempo de fin en milisegundos
        double durationInSeconds = (endTime - startTime) / 1000.0; // Calcular la duración en segundos

        // Mostrar el tiempo en el JTextArea
        traspasosFrame.getTextM().setText("Tiempo de operación: " + durationInSeconds + " segundos");

        traspasosFrame.poblarTabla(); // Actualizar la tabla de traspasos
        dispose(); // Cerrar el JFrame
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al procesar la operación: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panelito = new javax.swing.JPanel();
        P = new javax.swing.JLabel();
        D = new javax.swing.JLabel();
        N = new javax.swing.JLabel();
        MA = new javax.swing.JLabel();
        MO = new javax.swing.JLabel();
        A = new javax.swing.JLabel();
        M = new javax.swing.JLabel();
        OK = new javax.swing.JButton();
        DpiAnterior = new javax.swing.JTextField();
        Placa = new javax.swing.JTextField();
        NombreNuevo = new javax.swing.JTextField();
        NombreAnterior = new javax.swing.JTextField();
        Fecha = new javax.swing.JTextField();
        DpiNuevo = new javax.swing.JTextField();
        Departamento = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panelito.setBackground(new java.awt.Color(0, 51, 204));

        P.setText("Placa");

        D.setText("DPI ant.");

        N.setText("Nombre ant.");

        MA.setText("Fecha");

        MO.setText("DPI Nuevo");

        A.setText("Nombre Nuevo");

        M.setText("Departamento");

        OK.setText("Agregar");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });

        Placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaActionPerformed(evt);
            }
        });

        NombreNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreNuevoActionPerformed(evt);
            }
        });

        NombreAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreAnteriorActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelitoLayout = new javax.swing.GroupLayout(Panelito);
        Panelito.setLayout(PanelitoLayout);
        PanelitoLayout.setHorizontalGroup(
            PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelitoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(N)
                    .addComponent(P)
                    .addComponent(D)
                    .addComponent(MA)
                    .addGroup(PanelitoLayout.createSequentialGroup()
                        .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A)
                            .addComponent(M)
                            .addComponent(MO))
                        .addGap(24, 24, 24)
                        .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DpiNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(NombreAnterior)
                            .addComponent(Placa)
                            .addComponent(DpiAnterior)
                            .addComponent(Fecha)
                            .addComponent(NombreNuevo)
                            .addComponent(Departamento))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelitoLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelitoLayout.createSequentialGroup()
                        .addComponent(Salir)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelitoLayout.createSequentialGroup()
                        .addComponent(OK)
                        .addGap(167, 167, 167))))
        );
        PanelitoLayout.setVerticalGroup(
            PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelitoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Salir)
                .addGap(24, 24, 24)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P)
                    .addComponent(Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D)
                    .addComponent(DpiAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(N)
                    .addComponent(NombreAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MA)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DpiNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MO))
                .addGap(18, 18, 18)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A))
                .addGap(18, 18, 18)
                .addGroup(PanelitoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(M)
                    .addComponent(Departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(OK)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
crearOModificarTraspaso();  
    }//GEN-LAST:event_OKActionPerformed

    private void PlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaActionPerformed

    }//GEN-LAST:event_PlacaActionPerformed

    private void NombreNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreNuevoActionPerformed

    private void NombreAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreAnteriorActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel A;
    private javax.swing.JLabel D;
    private javax.swing.JTextField Departamento;
    private javax.swing.JTextField DpiAnterior;
    private javax.swing.JTextField DpiNuevo;
    private javax.swing.JTextField Fecha;
    private javax.swing.JLabel M;
    private javax.swing.JLabel MA;
    private javax.swing.JLabel MO;
    private javax.swing.JLabel N;
    private javax.swing.JTextField NombreAnterior;
    private javax.swing.JTextField NombreNuevo;
    private javax.swing.JButton OK;
    private javax.swing.JLabel P;
    private javax.swing.JPanel Panelito;
    private javax.swing.JTextField Placa;
    private javax.swing.JButton Salir;
    // End of variables declaration//GEN-END:variables
}
